apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "grafana.name" . }}-chown"
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  # 硬策略
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - grafana
            topologyKey: kubernetes.io/hostname

      restartPolicy: Never
      containers:
      - name: grafana-chown
        command: 
        - "bin/sh"
        - "-c"
        - "chown -R 472:472 /var/lib/grafana && echo '[INFO]: init SuccessFuly.'"
        
        image: "{{ .Values.grafana.permissions.imageRepository }}:{{ .Values.grafana.permissions.imageTag }}"
        imagePullPolicy: {{ .Values.grafana.permissions.imagePullPolicy }}
        volumeMounts:
        - name: grafana-storage
          subPath: grafana
          mountPath: /var/lib/grafana
      volumes:
      {{- if .Values.grafana.storageSpec }}
      - name: grafana-storage
      {{- toYaml .Values.grafana.storageSpec | nindent 8 }}
      {{- else }}
      - name: grafana-storage
        hostPath:
          path: /data/monitoring/grafana
      {{- end }}