apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
   {{- include "loki.labels" . | nindent 4 }}
data:
  loki.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.config . | fromYaml)  | toYaml) . | nindent 4 }}
