kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: prometheus-rules
  namespace: {{ .Values.global.namespace }}
data: 
  prometheus-rules.yml: |
    groups:
      - name: example
        rules:
        - alert: kube-proxy的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{job=~"kubernetes-kube-proxy"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.job}}`}}组件的cpu使用率超过80%"
        - alert: scheduler的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{job=~"kubernetes-schedule"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.job}}`}}组件的cpu使用率超过80%"
        - alert: controller-manager的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{job=~"kubernetes-controller-manager"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.job}}`}}组件的cpu使用率超过80%"
        - alert: apiserver的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{job=~"kubernetes-apiserver"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.job}}`}}组件的cpu使用率超过80%"
        - alert: etcd的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{job=~"kubernetes-etcd"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.job}}`}}组件的cpu使用率超过80%"
        - alert: kube-state-metrics的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{k8s_app=~"kube-state-metrics"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.k8s_app}}`}}组件的cpu使用率超过80%"
            value: "{{`{{ $value }}`}}%"
            threshold: "80%"      
        - alert: coredns的cpu使用率大于80%
          expr: rate(process_cpu_seconds_total{k8s_app=~"kube-dns"}[1m]) * 100 > 80
          for: 2s
          labels:
            severity: warnning
          annotations:
            description: "{{`{{$labels.instance}}`}}的{{`{{$labels.k8s_app}}`}}组件的cpu使用率超过80%"
            value: "{{`{{ $value }}`}}%"
            threshold: "80%"      

      - name: 物理节点状态-监控告警
        rules:
        - alert: 物理节点cpu使用率
          expr: 100-avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)*100 > 80
          for: 2s
          labels:
            severity: critical
          annotations:
            summary: "{{`{{ $labels.instance }}`}}cpu使用率过高"
            description: "{{`{{ $labels.instance }}`}}的cpu使用率超过80%,当前使用率[{{`{{ $value }}`}}],需要排查处理" 
        - alert: 物理节点内存使用率
          expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 80
          for: 2s
          labels:
            severity: critical
          annotations:
            summary: "{{`{{ $labels.instance }}`}}内存使用率过高"
            description: "{{`{{ $labels.instance }}`}}的内存使用率超过80%,当前使用率[{{`{{ $value }}`}}],需要排查处理"
        - alert: Exporter Componen is Down
          expr: up == 0
          for: 1m
          labels:
            severity: serious
          annotations:
            summary: "节点: {{ $labels.instance }} Exporter 程序"
            description: "节点: {{ $labels.instance }} Exporter程序异常 请及时处理！."
        - alert: 物理节点磁盘的IO性能
          expr: 100-(avg(irate(node_disk_io_time_seconds_total[1m])) by(instance)* 100) < 60
          for: 2s
          labels:
            severity: critical
          annotations:
            summary: "{{`{{$labels.mountpoint}}`}} 流入磁盘IO使用率过高! "
            description: "{{`{{$labels.mountpoint }}`}} 流入磁盘IO大于60%(目前使用:{{`{{$value}}`}})"
        - alert: 磁盘容量
          expr: 100-(node_filesystem_free_bytes{fstype=~"ext4|xfs"}/node_filesystem_size_bytes {fstype=~"ext4|xfs"}*100) > 80
          for: 2s
          labels:
            severity: critical
          annotations:
            summary: "{{`{{$labels.mountpoint}}`}} 磁盘分区使用率过高！"
            description: "{{`{{$labels.mountpoint }}`}} 磁盘分区使用大于80%(目前使用:{{`{{$value}}`}}%)"

      - name: 业务服务接口-监控告警
        rules:
        - alert: 服务接口状态
          expr: InterfaceStatusCode != 200
          for: 2s
          labels:
            severity: critical
          annotations:
            summary: "「{{`{{ $labels.name }}`}}」接口异常"
            description: "命名空间: {{`{{ $labels.namespace }}`}}, SVC:「{{`{{ $labels.name }}`}}」接口「{{`{{ $value }}`}}」异常!" 

      - name: Ceph存储-监控告警
        rules:
        - alert: Ceph集群不健康
          expr: ceph_health_status != 0
          for: 2s
          labels:
            severity: critical
          annotations:
            description: "Warring: Ceph集群状态不健康「{{`{{ $labels.instance }}`}}」!"       

        - alert: Ceph Osd Down
          expr: ceph_osd_up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            description: "Ceph对象存储守护进程Down「{{`{{ $labels.ceph_daemon }}`}}」!"

        - alert: Ceph监视器时钟倾斜
          expr: abs(ceph_monitor_clock_skew_seconds) > 0.2
          for: 2m
          labels:
            severity: warning
          annotations:
            description: "检测到Ceph监视器时钟不同步, 请检查ntp和硬件时钟设置!"

        - alert: Ceph监视器空间不足
          expr: ceph_monitor_avail_percent < 10
          for: 2m
          labels:
            severity: warning
          annotations:
            description: "Ceph监视器存储不足!"

        - alert: Ceph Pg Down
          expr: ceph_pg_down > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            description: "Ceph pg down, 请确保所有数据都是可用的!"

      - name: Minio存储-监控告警
        rules:
        - alert: Minio 集群磁盘离线
          expr: minio_cluster_disk_offline_total > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            description: "Minio cluster disk is offline."

        - alert: Minio 集群节点离线
          expr: minio_cluster_nodes_offline_total > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            description: "Minio cluster node disk is offline."

        - alert: Minio 磁盘可用空间低于25%
          expr: disk_storage_available / disk_storage_total * 100 < 25
          for: 0m
          labels:
            severity: warning
          annotations:
            description: "Minio available free space is low (< 10%), The current: {{`{{ $value }}`}}"