kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: prometheus-rules
  namespace: {{ .Values.global.namespace }}
data:
    {{- toYaml .Values.prometheus.rules | nindent 2 }}