kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: {{ .Values.global.namespace }}
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 1s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'prometheusalert'
    receivers:
    - name: 'prometheusalert'
      webhook_configs:
      {{- if .Values.alertmanager.prometheusalertWebHook.feishu.enabled }}
      - url: "http://{{ include "prometheusAlert.name" . }}:{{ .Values.prometheusAlert.service.port }}/prometheusalert?type=fs&tpl=jsdesign&fsurl{{ .Values.alertmanager.prometheusalertWebHook.feishu.url }}"
      {{ end }}

    # 修改全家桶服务IP, 飞书机器人接口
    # http://[IP:Port]/prometheusalert?type=[类型]&tpl=[模版名]&fsurl[飞书机器人URL]