apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "alertmanager.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  serviceName: alertmanager
  selector:
    matchLabels:
      {{- include "alertmanager.labels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "alertmanager.labels" . | nindent 8 }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''

    spec:
      containers:
      - name: alertmanager
        image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
        imagePullPolicy: {{ .Values.alertmanager.image.imagePullPolicy }}
        ports:
        - containerPort: 9093

        {{- if .Values.alertmanager.readinessProbe }}
        readinessProbe:
          {{ toYaml .Values.alertmanager.readinessProbe.configure | nindent 12 }}
        {{ end }}

        resources:
          {{ toYaml .Values.alertmanager.resources | nindent 12 }}

        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: storage-volume
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime

      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: localtime
        hostPath:
          path: /etc/localtime
      {{- if .Values.alertmanager.storageSpec }}
      {{- toYaml .Values.alertmanager.storageSpec | nindent 4 }}
      {{- else }}
      - name: storage-volume
        hostPath:
          path: /data/monitoring/alertmanager
      {{- end }}

