kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: {{ .Values.global.namespace }}
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 1s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'prometheusalert'
    receivers:
    - name: 'prometheusalert'
      webhook_configs:
      {{- if .Values.alertmanager.prometheusalertWebHook.feishu.enabled }}
      - url: "http://{{ include "prometheusAlert.name" . }}:{{ .Values.prometheusAlert.service.port }}/prometheusalert?type=fs&tpl=feishu&fsurl={{ .Values.alertmanager.prometheusalertWebHook.feishu.url }}"
      {{- end }}
      {{- if .Values.alertmanager.prometheusalertWebHook.dingding.enabled }}
      - url: "http://{{ include "prometheusAlert.name" . }}:{{ .Values.prometheusAlert.service.port }}/prometheusalert?type=dd&tpl=dingding&ddurl={{ .Values.alertmanager.prometheusalertWebHook.dingding.url }}"
      {{- end }}
      {{- if .Values.alertmanager.prometheusalertWebHook.qywechat.enabled }}
      - url: "http://{{ include "prometheusAlert.name" . }}:{{ .Values.prometheusAlert.service.port }}/prometheusalert?type=wx&tpl=qywechat&wxurl={{ .Values.alertmanager.prometheusalertWebHook.qywechat.url }}"
      {{- end }}
      {{- if .Values.alertmanager.prometheusalertWebHook.email.enabled }}
      - url: "http://{{ include "prometheusAlert.name" . }}:{{ .Values.prometheusAlert.service.port }}/prometheusalert?type=email&tpl=email&email={{ .Values.alertmanager.prometheusalertWebHook.email.receiveEmailUser }}"
      {{- end }}

    # 修改全家桶服务IP, 飞书机器人接口
    # http://[IP:Port]/prometheusalert?type=[类型]&tpl=[模版名]&fsurl[飞书机器人URL]