{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.console.service.port }}
      protocol: TCP
      targetPort: 8080
      {{- if ( eq .Values.console.service.type "NodePort" ) }}
      nodePort: {{ .Values.console.service.nodePort }}
      {{- end }}
  selector:
    {{- include "console.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.console.service.type }}
{{- end }}