apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdb-check-pvc
  labels:
    app: rdb-check
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-check-pvc

  labels:
    app: cephfs-check
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-check-deployment

  labels:
    app: ceph-check
spec:
  selector:
    matchLabels:
      app: ceph-check
  template:
    metadata:
      labels:
        app: ceph-check
    spec:
      containers:
      - image: registry.js.design/rook-ceph/busybox:1.30
        name: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        env:
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        volumeMounts:
        - name: rdb-check-volume
          mountPath: /rdb-check-volume
        - name: cephfs-check-volume
          mountPath: /cephfs-check-volume
      volumes:
      - name: rdb-check-volume
        persistentVolumeClaim:
          claimName: rdb-check-pvc
      - name: cephfs-check-volume
        persistentVolumeClaim:
          claimName: cephfs-check-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-check-deployment2

  labels:
    app: ceph-check2
spec:
  selector:
    matchLabels:
      app: ceph-check2
  template:
    metadata:
      labels:
        app: ceph-check2
    spec:
      containers:
      - image: registry.js.design/rook-ceph/busybox:1.30
        name: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        volumeMounts:
        - name: cephfs-check-volume
          mountPath: /cephfs-check-volume
      volumes:
      - name: cephfs-check-volume
        persistentVolumeClaim:
          claimName: cephfs-check-pvc
