{{- if .Values.broker.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}-broker-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 5557
      protocol: TCP
      targetPort: 5557
  selector:
    {{- include "broker.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
{{- end }}
