apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}-broker-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http1
      port: {{ .Values.broker.service.port }}
      protocol: TCP
      targetPort: {{ .Values.broker.service.targetPort }}
    - name: http2
      port: 12911
      protocol: TCP
      targetPort: 12911
    - name: http3
      port: 12909
      protocol: TCP
      targetPort: 10909
  selector:
    {{- include "broker.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  

