{{- $replicaCount := int .Values.broker.replicas }}
{{- range $i := until $replicaCount }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" $ }}-broker-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "broker.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http1
      port: 4292{{ $i }}
      protocol: TCP
      targetPort: 4292{{ $i }}
      nodePort: 4292{{ $i }}
    - name: http2
      port: 4291{{ $i }}
      protocol: TCP
      targetPort: 4291{{ $i }}
      nodePort: 4291{{ $i }}
    - name: http3
      port: 42908
      protocol: TCP
      targetPort: 40908
      nodePort: null
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "broker.fullname" $ }}-broker-{{ $i }}
  sessionAffinity: None
---
{{- end }}

