{{- $replicaCount := int .Values.broker.replicas }}
{{- range $i := until $replicaCount }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" $ }}-broker-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "broker.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: broker
      port: {{ $.Values.broker.service.ports.broker }}
      protocol: TCP
      targetPort: 10910
      nodePort: {{ (add $.Values.broker.service.nodePorts.broker $i 1) }}
    - name: dledger
      port: {{ $.Values.broker.service.ports.dledger }}
      protocol: TCP
      targetPort: 20910
      nodePort: {{ (add $.Values.broker.service.nodePorts.dledger $i 1) }}
    - name: http
      port: 42908
      protocol: TCP
      targetPort: 40908
      nodePort: null
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "broker.fullname" $ }}-broker-{{ $i }}
  sessionAffinity: None
---
{{- end }}

