apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "broker.fullname" . }}-broker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "broker.fullname" . }}-broker-headless
  replicas: {{ .Values.broker.replicas }}
  selector:
    matchLabels:
      {{- include "broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "broker.labels" . | nindent 8 }}
    spec:
    {{- with .Values.broker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
      - name: broker 
        image: "{{ .Values.broker.image}}:{{ .Values.broker.imageTag }}"
        imagePullPolicy: {{ .Values.broker.imagePullPolicy }}

        command: ["/bin/sh"]
        # args: ["-c","tail -f /dev/null"]
        args: ["-c","sh /home/rocketmq/rocketmq-4.9.3/conf/setup.sh;sh mqbroker -c /home/rocketmq/rocketmq-4.9.3/conf/broker-prod.conf"]

        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JAVA_OPT_EXT
          value: {{ .Values.broker.config.javaOptExt }}

        ports:
        - name: http
          containerPort: {{ .Values.broker.service.targetPort }}
          protocol: TCP

        {{- if .Values.broker.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
              - ls
              - /assets
          {{- toYaml .Values.broker.readinessProbe.config | nindent 10 }}
        {{- end }}

        {{- if .Values.broker.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml .Values.broker.livenessProbe.config | nindent 10 }}
        {{- end }}

        resources:
          {{- toYaml .Values.broker.resources | nindent 10 }}

        volumeMounts:
          - name: host-time
            mountPath: /etc/localtime
          - name: logs
            mountPath: /home/rocketmq/logs
          - name: store
            mountPath: /home/rocketmq/store
          - name: conf
            mountPath: /home/rocketmq/rocketmq-4.9.3/conf/broker.conf
            subPath: broker.conf
          - name: conf
            mountPath: /home/rocketmq/rocketmq-4.9.3/conf/logback_broker.xml
            subPath: logback_broker.xml
          - name: conf
            mountPath: /home/rocketmq/rocketmq-4.9.3/conf/setup.sh
            subPath: setup.sh
      
      {{- if .Values.broker.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.broker.metrics.image}}:{{ .Values.broker.metrics.imageTag }}"
        imagePullPolicy: {{ .Values.broker.metrics.imagePullPolicy }}
        args:
        # - "--rocketmq.config.namesrvAddr={{ include "namesrv.fullname" . }}-namesrv:9876"
        - "--rocketmq.config.namesrvAddr=rocketmq-namesrv-0.rocketmq-namesrv-headless.default:9876;rocketmq-namesrv-1.rocketmq-namesrv-headless.default:9876;rocketmq-namesrv-2.rocketmq-namesrv-headless.default:9876"
        ports:
        - name: http
          containerPort: 5557
          protocol: TCP
      {{- end }}

      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: conf
          configMap:
            defaultMode: 420
            name: {{ include "broker.fullname" . }}-broker
        - name: store
          hostPath:
            path: /opt/rocketmq/store
        - name: logs
          hostPath:
            path: /opt/rocketmq/logs
          

      {{- with .Values.broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    {{- if .Values.broker.podAntiAffinityEnabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "broker.selectorLabels" . | nindent 20 }}
              weight: 1
    {{- end }}

          
    {{- with .Values.broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}