apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  default.conf : |-

    server {
        listen       80;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
      }

  nginx.conf : |-

    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log debug;
    pid        /var/run/nginx.pid;
    include /etc/nginx/modules.conf;

    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;
        real_ip_recursive on;
        set_real_ip_from 10.233.0.0/16;
        real_ip_header X-Real-IP;
        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/conf.d/upstream/*.conf;
    }
    stream{
      upstream namesrv{
          server rocketmq-namesrv-0.rocketmq-namesrv-headless:9876 weight=5 max_fails=3 fail_timeout=30s;
          server rocketmq-namesrv-1.rocketmq-namesrv-headless:9876 weight=5 max_fails=3 fail_timeout=30s;
          server rocketmq-namesrv-2.rocketmq-namesrv-headless:9876 weight=5 max_fails=3 fail_timeout=30s;
      }
      server{
        listen 9888;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass namesrv;
      }
    }






