apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "proxy.labels" . | nindent 8 }}
    spec:
    {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: proxy
          image: "{{ .Values.proxy.image}}:{{ .Values.proxy.imageTag }}"
          imagePullPolicy: {{ .Values.proxy.imagePullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.targetPort }}
              protocol: TCP

          {{- if .Values.proxy.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health/check
              port: {{ .Values.proxy.service.targetPort }}
              httpHeaders:
                - name: Referer
                  value: health_check
              {{- toYaml .Values.proxy.readinessProbe.config | nindent 12 }}
          {{- end }}

          {{- if .Values.proxy.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health/check
              port: {{ .Values.proxy.service.targetPort }}
              httpHeaders:
                - name: Referer
                  value: health_check
              {{- toYaml .Values.proxy.ivenessProbe.config | nindent 12 }}
            {{- end }}
            
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}

          volumeMounts:
          - name: config 
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf 
          - name: config 
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf

      volumes:
      - name: config 
        configMap:
          name: {{ include "proxy.fullname" . }}

    {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- if .Values.proxy.podAntiAffinityEnabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "proxy.selectorLabels" . | nindent 20 }}
              weight: 1
    {{- end }}
              
    {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}