apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "node-exporter.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
  {{- include "node-exporter.labels" . | nindent 4 }}
    
spec:
  selector:
    matchLabels:
    {{- include "node-exporter.labels" . | nindent 6 }}
     
  template:
    metadata:
      labels:
      {{- include "node-exporter.labels" . | nindent 8 }}
        
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: "{{ .Chart.Name }}-node-exporter"
        image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
        imagePullPolicy: {{ .Values.nodeExporter.image.imagePullPolicy }}

        ports:
        - containerPort: 9100

        resources:
          {{- toYaml .Values.nodeExporter.resources | nindent 10 }}

        securityContext:
          privileged: true

        args:
        - --path.procfs
        - /host/proc
        - --path.sysfs
        - /host/sys
        - --collector.filesystem.ignored-mount-points
        - '"^/(sys|proc|dev|host|etc)($|/)"'
        
        volumeMounts:
        - name: dev
          mountPath: /host/dev
        - name: proc
          mountPath: /host/proc
        - name: sys
          mountPath: /host/sys
        - name: rootfs
          mountPath: /rootfs
          
      tolerations:
      {{- toYaml .Values.nodeExporter.tolerations | nindent 6 }}
        
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /