
namesrv:

  image: "apache/rocketmq"
  imageTag: "4.9.3"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  config:
    javaOptExt: -Xms4096M -Xmx4096M -Xmn1024m

  replicas: 3

  service:
    type: ClusterIP
    port: 9876
    targetPort: 9876
    nodePort: 29876

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1m
      memory: 1Gi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}

console:

  image: "apacherocketmq/rocketmq-console"
  imageTag: "2.0.0"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  replicas: 3

  service:
    port: 8080
    targetPort: 8080
    type: NodePort
    nodePort: "28080"

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}

broker:

  image: "apache/rocketmq"
  imageTag: "4.9.3"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  config:
    javaOptExt: -Xms4096M -Xmx4096M -Xmn1024m

  replicas: 3

  service:
    port: 40911
    targetPort: 40911
    nodePort: 40911

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1m
      memory: 2Gi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 100Gi
    accessModes:
    - ReadWriteOnce

  metrics:
    enabled: true
    image: "sawyerlan/rocketmq-exporter"
    imageTag: "latest"
    imagePullSecrets: []
    imagePullPolicy: IfNotPresent

proxy:

  image: "registry.js.design/nginx/js-design-sourcecode-nginx-v2"
  imageTag: "1.18.0"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  replicas: 3

  service:
    port: 9888
    targetPort: 9888
    nodePort: 29888

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 100Mi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}