
namesrv:

  image: "apache/rocketmq"
  imageTag: "4.9.3"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  config:
    javaOptExt: -Xms4096M -Xmx4096M -Xmn1024m

  replicas: 1

  service:
    ports:
      namesrv: 9876
    nodePorts:
      namesrv: 29876

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1m
      memory: 1Gi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}

console:

  image: "apacherocketmq/rocketmq-console"
  imageTag: "2.0.0"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  replicas: 1

  service:
    type: NodePort
    port: 8080
    nodePort: "28080"

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}

broker:

  image: "apache/rocketmq"
  imageTag: "4.9.3"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  config:
    javaOptExt: -Xms4096M -Xmx4096M -Xmn1024m

  replicas: 1

  service:
    ports:
      broker: 10910
      dledger: 20910
    nodePorts:
      broker: 30910
      dledger: 40910

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1m
      memory: 2Gi

  nodeSelector: []

  tolerations: []

  podAntiAffinityEnabled: {}

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 100Gi
    accessModes:
    - ReadWriteOnce

  metrics:
    enabled: true
    image: "sawyerlan/rocketmq-exporter"
    imageTag: "latest"
    imagePullSecrets: []
    imagePullPolicy: IfNotPresent
