global:
  # 集群名称
  brokerClusterName: DefaultCluster
  # broker 名称, master 和 slave 使用相同的名称
  brokerName: broker-dledger01
  # 默认不填, 则会加入到当前集群自建的 namesrv 集群中, 如果填写指定的 namesrv 集群, 则会加入到指定的集群中.
  namesrvAddr: ""

namesrv:
  enabled: true
  image: "apache/rocketmq"
  imageTag: "4.9.3"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  config:
    javaOptExt: -Xms128M -Xmx4096M -Xmn128m

  replicas: 1

  service:
    ports:
      namesrv: 9876
    nodePorts:
      namesrv: 29876

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1m
      memory: 256Mi

  nodeSelector: []

  tolerations: []

  # pod 软亲和
  podAntiAffinityEnabled: true

  # node 硬亲和
  nodeAffinity:
  # - key: "rocketmq"
  #   operator: In
  #   values:
  #   - "true"

console:
  enabled: true
  image: "apacherocketmq/rocketmq-console"
  imageTag: "2.0.0"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  replicas: 1

  service:
    type: NodePort
    port: 8080
    nodePort: "28080"

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 50m
      memory: 32Mi

  nodeSelector: []

  tolerations: []

  # pod 软亲和
  podAntiAffinityEnabled: true

  # node 硬亲和
  nodeAffinity:
  # - key: "rocketmq"
  #   operator: In
  #   values:
  #   - "true"

broker:
  enabled: true
  image: "apache/rocketmq"
  imageTag: "4.9.3"
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent

  config:
    javaOptExt: -Xms32M -Xmx4096M -Xmn256m

  replicas: 1

  service:
    ports:
      broker: 30910
      dledger: 40910

  readinessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  livenessProbe:
    enabled: false
    config:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 3

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1m
      memory: 32Mi

  nodeSelector: []

  tolerations: []

  # pod 软亲和
  podAntiAffinityEnabled: true

  # node 硬亲和
  nodeAffinity:
  # - key: "rocketmq"
  #   operator: In
  #   values:
  #   - "true"

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 100Gi
    accessModes:
    - ReadWriteOnce

  metrics:
    enabled: true
    image: "sawyerlan/rocketmq-exporter"
    imageTag: "latest"
    imagePullSecrets: []
    imagePullPolicy: IfNotPresent
