apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.SvcType }}
