{{- $replicaCount := int .Values.namesrv.replicas }}
{{- range $i := until $replicaCount }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "namesrv.fullname" $ }}-namesrv-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "namesrv.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ $.Values.namesrv.service.port }}
      protocol: TCP
      targetPort: {{ $.Values.namesrv.service.targetPort }}
      nodePort: 2987{{ $i }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "namesrv.fullname" $ }}-namesrv-{{ $i }}
  sessionAffinity: None
---
{{- end }}

