apiVersion: v1
kind: Service
metadata:
  name: {{ include "namesrv.fullname" . }}-namesrv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namesrv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.namesrv.service.port }}
      protocol: TCP
      targetPort: {{ .Values.namesrv.service.targetPort }}
  selector:
    {{- include "namesrv.selectorLabels" . | nindent 4 }}


