{{- if .Values.namesrv.enabled }}
{{- $replicaCount := int .Values.namesrv.replicas }}
{{- range $i := until $replicaCount }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "namesrv.fullname" $ }}-namesrv-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "namesrv.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ $.Values.namesrv.service.ports.namesrv }}
      protocol: TCP
      targetPort: 9876
      nodePort: {{ (add $.Values.namesrv.service.nodePorts.namesrv $i 0) }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "namesrv.fullname" $ }}-namesrv-{{ $i }}
  sessionAffinity: None
---
{{- end }}
{{- end }}